routes/web.php
<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

//Route::get('/', [App\Http\Controllers\PagesController::class, 'home'])->name('home');

# 首页重定向
Route::redirect('/', '/products')->name('home');

Route::middleware(['auth', 'verified'])->group(
    function () {
        # 用户收货地址列表
        Route::get('user_addresses', [App\Http\Controllers\UserAddressesController::class, 'index'])
            ->name('user_addresses.index');
        # 创建收货地址表单
        Route::get('user_addresses/create', [App\Http\Controllers\UserAddressesController::class, 'create'])
            ->name('user_addresses.create');
        # 存储收货地址
        Route::post('user_addresses/store', [App\Http\Controllers\UserAddressesController::class, 'store'])
            ->name('user_addresses.store');
        # 编辑收货地址表单
        Route::get('user_addresses/{user_address}', [App\Http\Controllers\UserAddressesController::class, 'edit'])
            ->name('user_addresses.edit');
        # 更新收货地址
        Route::put('user_addresses/{user_address}', [App\Http\Controllers\UserAddressesController::class, 'update'])
            ->name('user_addresses.update');
        # 删除收货地址
        Route::delete('user_addresses/{user_address}', [App\Http\Controllers\UserAddressesController::class, 'destroy'])
            ->name('user_addresses.destroy');
        # 商品列表
        Route::get('products', [App\Http\Controllers\ProductsController::class, 'index'])
            ->name('products.index');
        # 收藏商品
        Route::post('products/{product}/favorite', [App\Http\Controllers\ProductsController::class, 'favor'])
            ->name('products.favor');
        # 取消收藏
        Route::delete('products/{product}/favorite', [App\Http\Controllers\ProductsController::class, 'disfavor'])
            ->name('products.disfavor');
        # 收藏列表
        Route::get('products/favorites', [App\Http\Controllers\ProductsController::class, 'favorites'])
            ->name('products.favorites');
        # 加入购物车
        Route::post('cart', [App\Http\Controllers\CartController::class, 'add'])
            ->name('cart.add');
        # 移除购物车商品
        Route::delete('cart/{sku}', [App\Http\Controllers\CartController::class, 'remove'])
            ->name('cart.remove');
        # 购物车列表
        Route::get('cart', [App\Http\Controllers\CartController::class, 'index'])
            ->name('cart.index');
    }
);

# 商品详情
Route::get('products/{product}', [App\Http\Controllers\ProductsController::class, 'show'])
    ->name('products.show');
Auth::routes(['verify' => true]);

app/Models/UserAddress.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @property mixed province
 * @property mixed city
 * @property mixed district
 * @property mixed address
 * @property int   user_id
 */
class UserAddress extends Model
{
    use HasFactory;

    protected $fillable = [
        'province',
        'city',
        'district',
        'address',
        'zip',
        'contact_name',
        'contact_phone',
        'last_used_at',
    ];

    protected $dates = ['last_used_at'];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function getFullAddressAttribute(): string
    {
        return "$this->province$this->city$this->district$this->address";
    }
}

app/Http/Controllers/UserAddressesController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\UserAddress;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use App\Http\Requests\UserAddressRequest;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Support\Facades\Cache;

class UserAddressesController extends Controller
{
    public function index(Request $request)
    {
        $addresses = Cache::remember('user_addresses_' . $request->user()->id, 5 * 3600, function () use ($request) {
            return $request->user()->addresses;
        });
        return view('user_addresses.index', compact('addresses'));
    }

    public function create()
    {
        return view('user_addresses.create_and_edit', ['address' => new UserAddress()]);
    }

    public function store(UserAddressRequest $request): RedirectResponse
    {
        $request->user()->addresses()->create(
            $request->only(
                [
                    'province',
                    'city',
                    'district',
                    'address',
                    'zip',
                    'contact_name',
                    'contact_phone',
                ]
            )
        );
        Cache::forget('user_addresses_' . $request->user()->id);
        return redirect()->route('user_addresses.index');
    }

    public function edit(UserAddress $userAddress)
    {
        return view('user_addresses.create_and_edit', ['address' => $userAddress]);
    }

    public function update(UserAddressRequest $request, UserAddress $userAddress): RedirectResponse
    {
        $userAddress->update(
            $request->only(
                [
                    'province',
                    'city',
                    'district',
                    'address',
                    'zip',
                    'contact_name',
                    'contact_phone',
                ]
            )
        );
        Cache::forget('user_addresses_' . $request->user()->id);
        return redirect()->route('user_addresses.index');
    }

    /**
     * @throws AuthorizationException
     */
    public function destroy(Request $request, UserAddress $userAddress): JsonResponse
    {
        $this->authorize('own', $userAddress);

        $userAddress->delete();
        Cache::forget('user_addresses_' . $request->user()->id);
        return response()->json(['success' => true]);
    }
}

resources/views/user_addresses/create_and_edit.blade.php
@extends('layouts.app')
@section('title', $address->id ? '编辑收货地址' : '新增收货地址')

@section('content')
  <div class="row">
    <div class="col-md-10 offset-lg-1">
      <div class="card">
        <div class="card-header">
          <h2 class="text-center">
            {{ $address->id ? '修改': '新增' }}收货地址
          </h2>
        </div>
        <div class="card-body">
          <!-- 输出后端报错开始 -->
          @if (count($errors) > 0)
            <div class="alert alert-danger">
              <h4>有错误发生：</h4>
              <ul>
                @foreach ($errors->all() as $error)
                  <li><i class="glyphicon glyphicon-remove"></i> {{ $error }}</li>
                @endforeach
              </ul>
            </div>
        @endif
        <!-- 输出后端报错结束 -->
          <!-- inline-template 代表通过内联方式引入组件 -->
          <user-addresses-create-and-edit inline-template>
            @if($address->id)
              <form class="form-horizontal" role="form" action="{{ route('user_addresses.update', ['user_address' => $address->id]) }}" method="post">
                {{method_field('PUT')}}
                @else
                  <form class="form-horizontal" role="form" action="{{ route('user_addresses.store') }}" method="post">
                  @endif
                  <!-- 引入 csrf token 字段 -->
                  {{ csrf_field() }}
                  <!-- 注意这里多了 @change -->
                    <select-district
                      :init-value="{{ json_encode([old('province', $address->province), old('city', $address->city), old('district', $address->district)]) }}"
                      @change="onDistrictChanged" inline-template>
                      <div class="form-group row">
                        <label class="col-form-label col-sm-2 text-md-right">省市区</label>
                        <div class="col-sm-3">
                          <select class="form-control" v-model="provinceId">
                            <option value="">选择省</option>
                            <option v-for="(name, id) in provinces" :value="id">@{{ name }}</option>
                          </select>
                        </div>
                        <div class="col-sm-3">
                          <select class="form-control" v-model="cityId">
                            <option value="">选择市</option>
                            <option v-for="(name, id) in cities" :value="id">@{{ name }}</option>
                          </select>
                        </div>
                        <div class="col-sm-3">
                          <select class="form-control" v-model="districtId">
                            <option value="">选择区</option>
                            <option v-for="(name, id) in districts" :value="id">@{{ name }}</option>
                          </select>
                        </div>
                      </div>
                    </select-district>
                    <!-- 插入了 3 个隐藏的字段 -->
                    <!-- 通过 v-model 与 user-addresses-create-and-edit 组件里的值关联起来 -->
                    <!-- 当组件中的值变化时，这里的值也会跟着变 -->
                    <input type="hidden" name="province" v-model="province">
                    <input type="hidden" name="city" v-model="city">
                    <input type="hidden" name="district" v-model="district">
                    <div class="form-group row">
                      <label class="col-form-label text-md-right col-sm-2">详细地址</label>
                      <div class="col-sm-9">
                        <input type="text" class="form-control" name="address"
                               value="{{ old('address', $address->address) }}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label class="col-form-label text-md-right col-sm-2">邮编</label>
                      <div class="col-sm-9">
                        <input type="text" class="form-control" name="zip" value="{{ old('zip', $address->zip) }}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label class="col-form-label text-md-right col-sm-2">姓名</label>
                      <div class="col-sm-9">
                        <input type="text" class="form-control" name="contact_name"
                               value="{{ old('contact_name', $address->contact_name) }}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label class="col-form-label text-md-right col-sm-2">电话</label>
                      <div class="col-sm-9">
                        <input type="text" class="form-control" name="contact_phone"
                               value="{{ old('contact_phone', $address->contact_phone) }}">
                      </div>
                    </div>
                    <div class="form-group row text-center">
                      <div class="col-12">
                        <button type="submit" class="btn btn-primary">提交</button>
                      </div>
                    </div>
                  </form>
          </user-addresses-create-and-edit>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/user_addresses/index.blade.php
@extends('layouts.app')

@section('title', '收货地址列表')

@section('content')
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="card panel-default">
        <div class="card-header">
          收货地址列表
          <a href="{{ route('user_addresses.create') }}" class="float-right">新增收货地址</a>
        </div>
        <div class="card-body">
          <table class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>收货人</th>
              <th>地址</th>
              <th>邮编</th>
              <th>电话</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            @foreach($addresses as $key => $address)
              <tr>
                <td>{{ $address->contact_name }}</td>
                <td>{{ $address->full_address }}</td>
                <td>{{ $address->zip }}</td>
                <td>{{ $address->contact_phone }}</td>
                <td>
                  <a href="{{route('user_addresses.edit', ['user_address' => $address->id])}}" class="btn btn-primary">修改</a>
                  <button class="btn btn-danger btn-del-address" type="button" data-id="{{ $address->id }}">删除</button>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
@stop

@section('scriptsAfterJs')
  <script>
    $(document).ready(function () {
      // 删除按钮点击事件
      $('.btn-del-address').click(function () {
        // 获取按钮上 data-id 属性的值，也就是地址 ID
        let id = $(this).data('id');
        // 调用 sweetalert
        swal({
          title: "确认要删除该地址？",
          icon: "warning",
          buttons: ['取消', '确定'],
          dangerMode: true,
        }).then(function (willDelete) { // 用户点击按钮后会触发这个回调函数
          // 用户点击确定 willDelete 值为 true， 否则为 false
          // 用户点了取消，啥也不做
          if (!willDelete) {
            return;
          }
          // 调用删除接口，用 id 来拼接出请求的 url
          axios.delete('/user_addresses/' + id)
            .then(function () {
              // 请求成功之后重新加载页面
              location.reload();
            })
        });
      });
    });
  </script>
@endsection