routes/web.php
<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

//Route::get('/', [App\Http\Controllers\PagesController::class, 'home'])->name('home');

# 首页重定向
Route::redirect('/', '/products')->name('home');

Route::middleware(['auth', 'verified'])->group(
    function () {
        # 用户收货地址列表
        Route::get('user_addresses', [App\Http\Controllers\UserAddressesController::class, 'index'])
            ->name('user_addresses.index');
        # 创建收货地址表单
        Route::get('user_addresses/create', [App\Http\Controllers\UserAddressesController::class, 'create'])
            ->name('user_addresses.create');
        # 存储收货地址
        Route::post('user_addresses/store', [App\Http\Controllers\UserAddressesController::class, 'store'])
            ->name('user_addresses.store');
        # 编辑收货地址表单
        Route::get('user_addresses/{user_address}', [App\Http\Controllers\UserAddressesController::class, 'edit'])
            ->name('user_addresses.edit');
        # 更新收货地址
        Route::put('user_addresses/{user_address}', [App\Http\Controllers\UserAddressesController::class, 'update'])
            ->name('user_addresses.update');
        # 删除收货地址
        Route::delete('user_addresses/{user_address}', [App\Http\Controllers\UserAddressesController::class, 'destroy'])
            ->name('user_addresses.destroy');
        # 商品列表
        Route::get('products', [App\Http\Controllers\ProductsController::class, 'index'])
            ->name('products.index');
        # 收藏商品
        Route::post('products/{product}/favorite', [App\Http\Controllers\ProductsController::class, 'favor'])
            ->name('products.favor');
        # 取消收藏
        Route::delete('products/{product}/favorite', [App\Http\Controllers\ProductsController::class, 'disfavor'])
            ->name('products.disfavor');
        # 收藏列表
        Route::get('products/favorites', [App\Http\Controllers\ProductsController::class, 'favorites'])
            ->name('products.favorites');
        # 加入购物车
        Route::post('cart', [App\Http\Controllers\CartController::class, 'add'])
            ->name('cart.add');
        # 移除购物车商品
        Route::delete('cart/{sku}', [App\Http\Controllers\CartController::class, 'remove'])
            ->name('cart.remove');
        # 购物车列表
        Route::get('cart', [App\Http\Controllers\CartController::class, 'index'])
            ->name('cart.index');
    }
);

# 商品详情
Route::get('products/{product}', [App\Http\Controllers\ProductsController::class, 'show'])
    ->name('products.show');
Auth::routes(['verify' => true]);

app/Models/Product.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Encore\Admin\Traits\DefaultDatetimeFormat;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @property mixed on_sale
 * @property mixed id
 */
class Product extends Model
{
    use HasFactory, DefaultDatetimeFormat;

    protected $fillable = [
        'title',
        'description',
        'image',
        'on_sale',
        'rating',
        'sold_count',
        'review_count',
        'price',
    ];

    protected $casts = [
        'on_sale' => 'boolean', // on_sale 是一个布尔类型的字段
    ];

    public function skus(): HasMany
    {
        return $this->hasMany(ProductSku::class);
    }

    public function getImageUrlAttribute()
    {
        // 如果 image 字段本身就已经是完整的 url 就直接返回
        if(Str::startsWith($this->attributes['image'], ['http://', 'https://'])){
            return $this->attributes['image'];
        }
        return Storage::disk('public')->url($this->attributes['image']);
    }
}

app/Http/Controllers/ProductsController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers;

use App\Exceptions\InvalidRequestException;
use App\Models\Product;
use App\Http\Requests\Request;

class ProductsController extends Controller
{
    public function index(Request $request)
    {
        $builder = Product::query()->where('on_sale', true);
        if ($search = $request->input('search', '')) {
            $like = '%' . $search . '%';
            $builder->where(
                function ($query) use ($like) {
                    $query->where('title', 'like', $like)
                        ->orWhereHas(
                            'skus',
                            function ($query) use ($like) {
                                $query->where('title', 'like', $like);
                            }
                        );
                }
            );
        }
        if ($order = $request->input('order', '')) {
            if (preg_match('/^(.+)_(asc|desc)$/', $order, $m)) {
                // 如果字符串的开头是这 3 个字符串之一，说明是一个合法的排序值
                if (in_array($m[1], ['price', 'sold_count', 'rating'])) {
                    // 根据传入的排序值来构造排序参数
                    $builder->orderBy($m[1], $m[2]);
                }
            }
        }
        $products = $builder->paginate(16);
        $filters = compact('search', 'order');
        return view('products.index', compact('products', 'filters'));
    }

    /**
     * @throws InvalidRequestException
     */
    public function show(Product $product, Request $request)
    {
        if (!$product->on_sale) {
            throw new InvalidRequestException('商品未上架');
        }
        $favored = false;
        if ($user = $request->user()) {
            $favored = (bool)$user->favoriteProducts()->find($product->id);
        }
        return view('products.show', compact('product', 'favored'));
    }

    public function favor(Product $product, Request $request): array
    {
        $user = $request->user();
        if ($user->favoriteProducts()->find($product->id)) {
            return [];
        }

        $user->favoriteProducts()->attach($product);

        return [];
    }

    public function disfavor(Product $product, Request $request): array
    {
        $user = $request->user();
        $user->favoriteProducts()->detach($product);

        return [];
    }

    public function favorites(Request $request)
    {
        $products = $request->user()->favoriteProducts()->paginate(16);

        return view('products.favorites', compact('products'));
    }
}

resources/views/products/favorites.blade.php
@extends('layouts.app')
@section('title', '我的收藏')

@section('content')
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <div class="card">
        <div class="card-header">我的收藏</div>
        <div class="card-body">
          <div class="row products-list">
            @foreach($products as $product)
              <div class="col-3 product-item">
                <div class="product-content">
                  <div class="top">
                    <div class="img">
                      <a href="{{ route('products.show', ['product' => $product->id]) }}">
                        <img src="{{ $product->image_url }}" alt="">
                      </a>
                    </div>
                    <div class="price"><b>￥</b>{{ $product->price }}</div>
                    <a href="{{ route('products.show', ['product' => $product->id]) }}">{{ $product->title }}</a>
                  </div>
                  <div class="bottom">
                    <div class="sold_count">销量 <span>{{ $product->sold_count }}笔</span></div>
                    <div class="review_count">评价 <span>{{ $product->review_count }}</span></div>
                  </div>
                </div>
              </div>
            @endforeach
          </div>
          <div class="float-right">{{ $products->render() }}</div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title', '商品列表')

@section('content')
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <div class="card">
        <div class="card-body">
          <form action="{{ route('products.index') }}" class="search-form">
            <div class="form-row">
              <div class="col-md-9">
                <div class="form-row">
                  <div class="col-auto">
                    <input type="text" class="form-control form-control-sm" name="search" placeholder="搜索"></div>
                  <div class="col-auto">
                    <button class="btn btn-primary btn-sm">搜索</button>
                  </div>
                </div>
              </div>
              <div class="col-md-3">
                <select name="order" class="form-control form-control-sm float-right">
                  <option value="">排序方式</option>
                  <option value="price_asc">价格从低到高</option>
                  <option value="price_desc">价格从高到低</option>
                  <option value="sold_count_desc" selected>销量从高到低</option>
                  <option value="sold_count_asc">销量从低到高</option>
                  <option value="rating_desc">评价从高到低</option>
                  <option value="rating_asc">评价从低到高</option>
                </select>
              </div>
            </div>
          </form>
          <div class="row products-list">
            @foreach($products as $product)
              <div class="col-3 product-item">
                <div class="product-content">
                  <div class="top">
                    <div class="img">
                      <a href="{{route('products.show', ['product' => $product->id])}}">
                        <img src="{{$product->image_url }}" alt="">
                      </a>
                    </div>
                    <div class="price"><b>￥</b>{{ $product->price }}</div>
                    <div class="title">
                      <a href="{{ route('products.show', ['product' => $product->id]) }}">{{ $product->title }}</a>
                    </div>
                  </div>
                  <div class="bottom">
                    <div class="sold_count">销量 <span>{{ $product->sold_count }}笔</span></div>
                    <div class="review_count">评价 <span>{{ $product->review_count }}</span></div>
                  </div>
                </div>
              </div>
            @endforeach
          </div>
          <div class="float-right">{{ $products->appends($filters)->render() }}</div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scriptsAfterJs')
  <script>
    let filters = {!! json_encode($filters, JSON_THROW_ON_ERROR) !!}
    $(document).ready(function () {
      $('.search-form input[name=search]').val(filters.search);
      let form_select = '.search-form select[name=order]';
      $(form_select).val(filters.order);

      $(form_select).on('change', function () {
        $('.search-form').submit();
      });
    })
  </script>
@stop

resources/views/products/show.blade.php
@extends('layouts.app')
@section('title', $product->title)

@section('content')
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <div class="card">
        <div class="card-body product-info">
          <div class="row">
            <div class="col-5">
              <img class="cover" src="{{ $product->image_url }}" alt="">
            </div>
            <div class="col-7">
              <div class="title">{{ $product->title }}</div>
              <div class="price"><label>价格</label><em>￥</em><span>{{ $product->price }}</span></div>
              <div class="sales_and_reviews">
                <div class="sold_count">累计销量 <span class="count">{{ $product->sold_count }}</span></div>
                <div class="review_count">累计评价 <span class="count">{{ $product->review_count }}</span></div>
                <div class="rating" title="评分 {{ $product->rating }}">评分 <span
                    class="count">{{ str_repeat('★', floor($product->rating)) }}{{ str_repeat('☆', 5 - floor($product->rating)) }}</span>
                </div>
              </div>
              <div class="skus">
                <label>选择</label>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                  @foreach($product->skus as $sku)
                    <label class="btn sku-btn"
                           data-toggle="tooltip"
                           data-placement="bottom"
                           title="{{ $sku->description }}"
                           data-price="{{$sku->price}}"
                           data-stock="{{$sku->stock}}">
                      <input type="radio" name="skus" autocomplete="off" value="{{ $sku->id }}"> {{ $sku->title }}
                    </label>
                  @endforeach
                </div>
              </div>
              <div class="cart_amount">
                <label>数量</label>
                <input type="text"
                       class="form-control form-control-sm"
                       value="1">
                <span>件</span>
                <span class="stock"></span>
              </div>
              <div class="buttons">
                @if($favored)
                  <button class="btn btn-success btn-disfavor">取消收藏</button>
                @else
                  <button class="btn btn-success btn-favor">❤ 收藏</button>
                @endif
                <button class="btn btn-primary btn-add-to-cart">加入购物车</button>
              </div>
            </div>
          </div>
          <div class="product-detail">
            <ul class="nav nav-tabs" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" href="#product-detail-tab" aria-controls="product-detail-tab" role="tab"
                   data-toggle="tab" aria-selected="true">商品详情</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#product-reviews-tab" aria-controls="product-reviews-tab" role="tab"
                   data-toggle="tab" aria-selected="false">用户评价</a>
              </li>
            </ul>
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="product-detail-tab">
                {!! $product->description !!}
              </div>
              <div role="tabpanel" class="tab-pane" id="product-reviews-tab">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@section('scriptsAfterJs')
  <script>
    $(document).ready(function () {
      $('[data-toggle="tooltip"]').tooltip({trigger: 'hover'});
      $('.sku-btn').click(function () {
        $('.product-info .price span').text($(this).data('price'));
        $('.product-info .stock').text('库存：' + $(this).data('stock') + '件');
      });

      $('.btn-favor').click(function () {
        axios.post('{{ route('products.favor', ['product' => $product->id]) }}')
          .then(function () {
            swal('操作成功', '', 'success').then(function () {
              location.reload();
            });
          }, function (error) {
            // 如果返回码是 401 代表没登录
            if (error.response && error.response.status === 401) {
              swal('请先登录', '', 'error');
            } else if (error.response && (error.response.data.msg || error.response.data.message)) {
              // 其他有 msg 或者 message 字段的情况，将 msg 提示给用户
              swal(error.response.data.msg ? error.response.data.msg : error.response.data.message, '', 'error');
            } else {
              // 其他情况应该是系统挂了
              swal('系统错误', '', 'error');
            }
          });
      });
      $('.btn-disfavor').click(() => {
        axios.delete('{{route('products.disfavor', ['product' => $product->id])}}').then(() => {
          swal('操作成功', '', 'success').then(() => {
            location.reload();
          });
        }, (e) => {
          console.log(e)
        }).catch((e) => {
          console.log(e)
        })
      });

      $('.btn-add-to-cart').click(function () {
        // 请求加入购物车接口
        axios.post('{{ route('cart.add') }}', {
          sku_id: $('label.active input[name=skus]').val(),
          amount: $('.cart_amount input').val(),
        })
          .then(function () { // 请求成功执行此回调
            swal('加入购物车成功', '', 'success').then(function () {
              location.href = '{{ route('cart.index') }}';
            });
          }, function (error) { // 请求失败执行此回调
            if (error.response.status === 401) {

              // http 状态码为 401 代表用户未登陆
              swal('请先登录', '', 'error');

            } else if (error.response.status === 422) {
              // http 状态码为 422 代表用户输入校验失败
              let html = '<div>';
              _.each(error.response.data.errors, function (errors) {
                _.each(errors, function (error) {
                  html += error + '<br>';
                })
              });
              html += '</div>';
              swal({content: $(html)[0], icon: 'error'})
            } else {
              // 其他情况应该是系统挂了
              swal('系统错误', '', 'error');
            }
          })
      });
    })
  </script>
@stop